name: Build openbabel-wheel

on:
  push:
    branches:
      - "**"
    paths:
      - "openbabel-wheel/**"
      - ".github/workflows/openbabel-wheel.yaml"
    tags:
      - "openbabel-wheel-[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels for cp${{ matrix.python }}-${{ matrix.platform_id }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python: 311
            platform_id: manylinux2014_x86_64
    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20
        env:
          CIBW_BUILD_VERBOSITY: 3
        with:
          package-dir: openbabel-wheel
